completed ffpstick startup script

diff --git a/init/ffpstick b/init/ffpstick
--- a/init/ffpstick
+++ b/init/ffpstick
@@ -25,6 +25,25 @@ start_cmd="couchpotato_start"
 stop_cmd="couchpotato_stop"
 status_cmd="couchpotato_status"
 
+wait_for_status()
+{
+    counter=$2
+    while [ ${counter} -gt 0 ]; do
+        daemon_status
+        [ $? -eq $1 ] && break
+        let counter=counter-1
+        sleep 1
+    done
+}
+
+daemon_status()
+{
+    if [ -f ${PID_FILE} ] && [ -d /proc/`cat ${PID_FILE}` ]; then
+        return 0
+    fi
+        return 1
+}
+
 couchpotato_start()
 {
     if [ -f ${PID_FILE} ] && [ -d /proc/`cat ${PID_FILE}` ]; then
@@ -38,27 +57,29 @@ couchpotato_start()
 
 couchpotato_stop()
 {
-	if [ -f $PID_FILE ] ; then
-	    echo "Stopping $NAME"
-	    /ffp/bin/kill -SIGINT ` cat $PID_FILE `
-	else
-	    echo "Cannot find $PID_FILE"
-	fi
+    if [ -f $PID_FILE ] ; then
+        echo "Stopping $NAME"
+        kill `cat ${PID_FILE}`
+        wait_for_status 1 20
+        rm -f ${PID_FILE}
+    else
+        echo "Cannot find $PID_FILE"
+    fi
 }
 
-# couchpotato_status()
-# {
-# 	local pid=` cat $pidfile 2>/dev/null `
-# 	if test -n "$pid"; then
-# 		if cat /proc/$pid/cmdline | grep transmission >/dev/null ; then
-# 		    [ "$1" == "silent" ] || echo "$name is running"
-# 		    return 0
-# 		fi
-# 		rm $pidfile
-# 	fi
+couchpotato_status()
+{
+	local pid=` cat ${PID_FILE} 2>/dev/null `
+	if test -n "$pid"; then
+		if cat /proc/$pid/cmdline | grep ${APP_PATH} >/dev/null ; then
+		    [ "$1" == "silent" ] || echo "$NAME is running"
+		    return 0
+		fi
+		rm $pidfile
+	fi
 	
-# 	[ "$1" == "silent" ] || echo "$name not running"
-# 	return 1
-# }
+	[ "$1" == "silent" ] || echo "$NAME not running"
+	return 1
+}
 
 run_rc_command "$1"
